apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: the-3scale-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: the-3scale-operator
    app.kubernetes.io/part-of: the-3scale-operator
  name: the-3scale-operator
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: the-3scale-operator
status:
  loadBalancer: {}
